app = "chat-server"

[[services]]
  internal_port = 54000
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 54000
    handlers = []
