# fly.toml app configuration file generated for chat-c on 2025-11-09T03:31:35Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chat-c'
primary_region = 'iad'

[build]

[[services]]
  protocol = "tcp"
  internal_port = 54000
  processes = ["app"]
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 54000
    handlers = []
